### ISSUE TITLE
Error in create_tiles.py 

### ISSUE THREAD

**Issue by bartekrdz** [aireveries/RarePlanes#9]
I am getting an error when trying to retile the rareplanes imagery as per the example in README (size 1024 and 0 overlap). I am using the provided docker image. 

The error message:

```
(solaris) root@88c16468cf66:/code# python tools/create_tiles.py --image_dir myplanes/real/train/PS-RGB --geojson_dir myplanes/real/train/geojson_aircraft --tile_image_dir myplanes/real/train/retiled_images --tile_geojson_dir myplanes/real/train/retiled_geojson --tile_size 1024 --overlap 0
/opt/conda/envs/solaris/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/opt/conda/envs/solaris/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/opt/conda/envs/solaris/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:528: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/opt/conda/envs/solaris/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:529: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/opt/conda/envs/solaris/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:530: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/opt/conda/envs/solaris/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:535: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
  0%|                                                                                                | 0/187 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "fiona/_shim.pyx", line 83, in fiona._shim.gdal_open_vector
  File "fiona/_err.pyx", line 270, in fiona._err.exc_wrap_pointer
fiona._err.CPLE_OpenFailedError: myplanes/real/train/geojson_aircraft/100_1040010029990A00.geojson: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tools/create_tiles.py", line 51, in <module>
    args.min_ratio)
  File "tools/create_tiles.py", line 22, in create_tiles
    min_obj_perc=min_obj_perc)
  File "/code/rareplanes/tiles.py", line 51, in rareplanes_tiler
    in_gdf = gpd.read_file(geojson)
  File "/opt/conda/envs/solaris/lib/python3.7/site-packages/geopandas/io/file.py", line 89, in read_file
    with reader(path_or_bytes, **kwargs) as features:
  File "/opt/conda/envs/solaris/lib/python3.7/site-packages/fiona/env.py", line 398, in wrapper
    return f(*args, **kwargs)
  File "/opt/conda/envs/solaris/lib/python3.7/site-packages/fiona/__init__.py", line 254, in open
    layer=layer, enabled_drivers=enabled_drivers, **kwargs)
  File "/opt/conda/envs/solaris/lib/python3.7/site-packages/fiona/collection.py", line 154, in __init__
    self.session.start(self, **kwargs)
  File "fiona/ogrext.pyx", line 484, in fiona.ogrext.Session.start
  File "fiona/_shim.pyx", line 90, in fiona._shim.gdal_open_vector
fiona.errors.DriverError: myplanes/real/train/geojson_aircraft/100_1040010029990A00.geojson: No such file or directory
```

The files are definitely in the specified folder

```
(solaris) root@88c16468cf66:/code/myplanes/real/train/PS-RGB# ls -l
total 48113556
-rwxrwxrwx 1 root root  306499462 Apr 10  2020 100_1040010029990A00.tif
-rwxrwxrwx 1 root root  373454738 Apr 10  2020 100_1040010039437200.tif
-rwxrwxrwx 1 root root  360376388 Apr 10  2020 100_1040010046CD1500.tif
-rwxrwxrwx 1 root root  132643059 Apr 10  2020 101_104001003BD74200.tif
-rwxrwxrwx 1 root root   42536924 Apr 10  2020 102_104001003C774900.tif
-rwxrwxrwx 1 root root   60378308 Apr 10  2020 102_104001003D82DC00.tif
```
```
(solaris) root@88c16468cf66:/code/myplanes/real/train/geojson_aircraft# ls -l
total 9432
-rwxrwxrwx 1 root root  15712 Apr 30  2020 100_1040010029990A00.geojson
-rwxrwxrwx 1 root root  21457 Apr 30  2020 100_1040010039437200.geojson
-rwxrwxrwx 1 root root  34571 Apr 30  2020 100_1040010046CD1500.geojson
-rwxrwxrwx 1 root root  14264 Apr 30  2020 101_104001003BD74200.geojson
-rwxrwxrwx 1 root root  14520 Apr 30  2020 102_104001003C774900.geojson
-rwxrwxrwx 1 root root  15408 Apr 30  2020 102_104001003D82DC00.geojson
-rwxrwxrwx 1 root root  27112 Apr 30  2020 103_10400100080A3000.geojson
-rwxrwxrwx 1 root root  14877 Apr 30  2020 103_104001004890F500.geojson
```

**Environment information**
Docker: Docker Desktop for Windows
OS: Ubuntu 20.04, WSL2
Python version: `3.7.6 `

**Comment by bartekrdz** [comment]
I tried to work around the error by using tiles.py and locally and local solaris environment on WSL2. 

I still get an error although slightly different:

```
  np_resource = np.dtype([("resource", np.ubyte, 1)])
  0%|                                                                                                                                                                           | 0/6 [00:00<?, ?it/s/home/bartek/anaconda3/envs/solaris/lib/python3.7/site-packages/solaris/tile/vector_tile.py:291: UserWarning: Geometry is in a geographic CRS. Results from 'area' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.

  gdf['origarea'] = gdf.area
/home/bartek/anaconda3/envs/solaris/lib/python3.7/site-packages/solaris/tile/vector_tile.py:307: UserWarning: Geometry is in a geographic CRS. Results from 'area' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.

  cut_gdf['partialDec'] = cut_gdf.area / cut_gdf['origarea']
  0%|                                                                                                                                                                          | 0/11 [00:00<?, ?it/s]
  0%|                                                                                                                                                                           | 0/6 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "fiona/_shim.pyx", line 110, in fiona._shim.gdal_create
  File "fiona/_err.pyx", line 270, in fiona._err.exc_wrap_pointer
fiona._err.CPLE_OpenFailedError: Failed to create GeoJSON datasource: datasets/real/train/retiled_geojson/1_104005000FDC8D00_tile_1.geojson: datasets/real/train/retiled_geojson/1_104005000FDC8D00_tile_1.geojson: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/c/Users/radzi/Downloads/main.py", line 81, in <module>
    rareplanes_tiler ('/mnt/c/Users/radzi/Downloads/datasets/real/train/PS-RGB', '/mnt/c/Users/radzi/Downloads/datasets/real/train/geojson_aircraft', 'datasets/real/train/retiled_images', 'datasets/real/train/retiled_geojson')
  File "/mnt/c/Users/radzi/Downloads/main.py", line 77, in rareplanes_tiler
    gdf.to_file(geojson_out, driver="GeoJSON")
  File "/home/bartek/anaconda3/envs/solaris/lib/python3.7/site-packages/geopandas/geodataframe.py", line 746, in to_file
    _to_file(self, filename, driver, schema, index, **kwargs)
  File "/home/bartek/anaconda3/envs/solaris/lib/python3.7/site-packages/geopandas/io/file.py", line 255, in _to_file
    filename, mode=mode, driver=driver, crs_wkt=crs_wkt, schema=schema, **kwargs
  File "/home/bartek/anaconda3/envs/solaris/lib/python3.7/site-packages/fiona/env.py", line 398, in wrapper
    return f(*args, **kwargs)
  File "/home/bartek/anaconda3/envs/solaris/lib/python3.7/site-packages/fiona/__init__.py", line 264, in open
    **kwargs)
  File "/home/bartek/anaconda3/envs/solaris/lib/python3.7/site-packages/fiona/collection.py", line 157, in __init__
    self.session.start(self, **kwargs)
  File "fiona/ogrext.pyx", line 944, in fiona.ogrext.WritingSession.start
  File "fiona/_shim.pyx", line 114, in fiona._shim.gdal_create
fiona.errors.DriverError: Failed to create GeoJSON datasource: datasets/real/train/retiled_geojson/1_104005000FDC8D00_tile_1.geojson: datasets/real/train/retiled_geojson/1_104005000FDC8D00_tile_1.geojson: No such file or directory
```

**Comment by jshermeyer** [comment]
Doesn't look like you're passing the full path of the files in for either of these cases.  Make sure your paths are exact and include all of the root directories.
